# =========================
# PostgreSQL Secret (untuk password)
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: poc-thread
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres