# ==========================================
# Loki ConfigMap
# ==========================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: poc-thread
data:
  config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_retain_period: 30s
      max_transfer_retries: 0
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/chunks
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks
    compactor:
      working_directory: /wal




