# ==========================================
# Loki Deployment
# ==========================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: poc-thread
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.1
          args:
            - -config.file=/etc/loki/config.yaml
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: wal
              mountPath: /wal
            - name: chunks
              mountPath: /loki/chunks
            - name: index
              mountPath: /loki/index
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: wal
          emptyDir: {}
        - name: chunks
          emptyDir: {}
        - name: index
          emptyDir: {}





