# ==========================================
# Loki Service (NodePort)
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: poc-thread
spec:
  type: NodePort
  selector:
    app: loki
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30100