spring:
  application:
    name: ms-thread-async

  profiles:
    active: local

server:
  port: 8081

async:
  log:
    core-pool-size: 10
    max-pool-size: 20
    queue-capacity: 5000

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
