spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demo_thread
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5       # jumlah koneksi minimal idle
      maximum-pool-size: 20 # jumlah koneksi maksimal
      idle-timeout: 30000   # ms sebelum koneksi idle dihapus
      max-lifetime: 1800000 # ms maksimal koneksi hidup
      connection-timeout: 30000 # ms tunggu koneksi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
