spring:
  application:
    name: ms-thread-leak

  profiles:
    active: local

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    id.co.bcafinance.msthreadleak: DEBUG
